"""empty message

Revision ID: 192c68fc2018
Revises: 
Create Date: 2024-11-12 11:15:40.579799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192c68fc2018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_comment', sa.String(), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shops.id'], name=op.f('fk_coupons_coffee_shop_id_coffee_shops')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('coffee_shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shops.id'], name=op.f('fk_reviews_coffee_shop_id_coffee_shops')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('coupons')
    op.drop_table('customers')
    op.drop_table('coffee_shops')
    # ### end Alembic commands ###
